module.exports = {
    REQUISITION_STATUS :{
        APPROVAL_PENDING:"APPROVAL_PENDING",
        APPROVED:"APPROVED",
        REJECTED:"REJECTED",
        IN_PROCESS:"IN_PROCESS",
        DELIVERED:"DELIVERED",
        PARTIALLY_DELIVERED:"PARTIALLY_DELIVERED",
    },
    ITEM_CATEGORIES:{
        CRITICAL:"CRITICAL",
        OTHER:"OTHER",
    }
}