module.exports = {
  REQUISITION_STATUS: {
    APPROVAL_PENDING: "APPROVAL_PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    IN_PROCESS: "IN_PROCESS",
    //
    ORDER_PLACED: "ORDER_PLACED",
    //
    DELIVERED: "DELIVERED",
    PARTIALLY_DELIVERED: "PARTIALLY_DELIVERED",
  },
  ITEM_CATEGORIES: {
    CRITICAL: "CRITICAL",
    OTHER: "OTHER",
  },
  PAY_STATUS: {
    PAID: "PAID",
    NOT_PAID: "NOT_PAID",
  },
  PRIORITY: {
    LOW: "LOW",
    MEDIUM: "MEDIUM",
    HIGH: "HIGH",
  },
};
